#!/bin/bash
#PBS -N ctsm6_lhc0360
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0360 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0361 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0362 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0363 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0364 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0365 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0366 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0367 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0368 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0369 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0370 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0371 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0372 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0373 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0374 /glade/derecho/scratch/djk2120/postp/c20250324/
