#!/bin/bash
#PBS -N ctsm6_lhc0465
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0465 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0466 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0467 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0468 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0469 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0470 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0471 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0472 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0473 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0474 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0475 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0476 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0477 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0478 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0479 /glade/derecho/scratch/djk2120/postp/c20250324/
