#!/bin/bash
#PBS -N ctsm6_lhc0645
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0645 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0646 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0647 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0648 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0649 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0650 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0651 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0652 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0653 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0654 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0655 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0656 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0657 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0658 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0659 /glade/derecho/scratch/djk2120/postp/c20250324/
