#!/bin/bash
#PBS -N ctsm6_lhc1275
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1275 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1276 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1277 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1278 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1279 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1280 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1281 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1282 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1283 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1284 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1285 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1286 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1287 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1288 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1289 /glade/derecho/scratch/djk2120/postp/c20250324/
