#!/bin/bash
#PBS -N ctsm6_lhc0975
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0975 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0976 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0977 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0978 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0979 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0980 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0981 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0982 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0983 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0984 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0985 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0986 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0987 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0988 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0989 /glade/derecho/scratch/djk2120/postp/c20250324/
