#!/bin/bash
#PBS -N ctsm6_lhc0870
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0870 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0871 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0872 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0873 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0874 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0875 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0876 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0877 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0878 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0879 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0880 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0881 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0882 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0883 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0884 /glade/derecho/scratch/djk2120/postp/c20250324/
