#!/bin/bash
#PBS -N ctsm6_lhc1320
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1320 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1321 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1322 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1323 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1324 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1325 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1326 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1327 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1328 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1329 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1330 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1331 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1332 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1333 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1334 /glade/derecho/scratch/djk2120/postp/c20250324/
