#!/bin/bash
#PBS -N ctsm6_lhc0720
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0720 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0721 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0722 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0723 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0724 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0725 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0726 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0727 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0728 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0729 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0730 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0731 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0732 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0733 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0734 /glade/derecho/scratch/djk2120/postp/c20250324/
