#!/bin/bash
#PBS -N ctsm6_lhc1305
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1305 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1306 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1307 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1308 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1309 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1310 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1311 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1312 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1313 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1314 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1315 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1316 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1317 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1318 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1319 /glade/derecho/scratch/djk2120/postp/c20250324/
