#!/bin/bash
#PBS -N ctsm6_lhc0000
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0000 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0001 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0002 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0003 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0004 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0005 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0006 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0007 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0008 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0009 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0010 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0011 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0012 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0013 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0014 /glade/derecho/scratch/djk2120/postp/c20250324/
