#!/bin/bash
#PBS -N ctsm6_lhc0060
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0060 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0061 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0062 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0063 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0064 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0065 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0066 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0067 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0068 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0069 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0070 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0071 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0072 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0073 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0074 /glade/derecho/scratch/djk2120/postp/c20250324/
