#!/bin/bash
#PBS -N ctsm6_lhc0180
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0180 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0181 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0182 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0183 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0184 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0185 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0186 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0187 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0188 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0189 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0190 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0191 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0192 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0193 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0194 /glade/derecho/scratch/djk2120/postp/c20250324/
