#!/bin/bash
#PBS -N ctsm6_lhc0705
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0705 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0706 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0707 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0708 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0709 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0710 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0711 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0712 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0713 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0714 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0715 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0716 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0717 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0718 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0719 /glade/derecho/scratch/djk2120/postp/c20250324/
