#!/bin/bash
#PBS -N ctsm6_lhc0120
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0120 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0121 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0122 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0123 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0124 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0125 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0126 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0127 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0128 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0129 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0130 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0131 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0132 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0133 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0134 /glade/derecho/scratch/djk2120/postp/c20250324/
