#!/bin/bash
#PBS -N ctsm6_lhc0240
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0240 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0241 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0242 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0243 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0244 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0245 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0246 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0247 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0248 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0249 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0250 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0251 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0252 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0253 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0254 /glade/derecho/scratch/djk2120/postp/c20250324/
