#!/bin/bash
#PBS -N ctsm6_lhc0030
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0030 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0031 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0032 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0033 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0034 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0035 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0036 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0037 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0038 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0039 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0040 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0041 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0042 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0043 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0044 /glade/derecho/scratch/djk2120/postp/c20250324/
