#!/bin/bash
#PBS -N ctsm6_lhc0750
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0750 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0751 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0752 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0753 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0754 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0755 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0756 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0757 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0758 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0759 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0760 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0761 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0762 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0763 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0764 /glade/derecho/scratch/djk2120/postp/c20250324/
