#!/bin/bash
#PBS -N ctsm6_lhc0570
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0570 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0571 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0572 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0573 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0574 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0575 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0576 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0577 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0578 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0579 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0580 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0581 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0582 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0583 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0584 /glade/derecho/scratch/djk2120/postp/c20250324/
