#!/bin/bash
#PBS -N ctsm6_lhc0450
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0450 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0451 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0452 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0453 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0454 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0455 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0456 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0457 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0458 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0459 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0460 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0461 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0462 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0463 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0464 /glade/derecho/scratch/djk2120/postp/c20250324/
