#!/bin/bash
#PBS -N ctsm6_lhc0960
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0960 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0961 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0962 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0963 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0964 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0965 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0966 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0967 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0968 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0969 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0970 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0971 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0972 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0973 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0974 /glade/derecho/scratch/djk2120/postp/c20250324/
