#!/bin/bash
#PBS -N ctsm6_lhc1050
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1050 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1051 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1052 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1053 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1054 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1055 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1056 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1057 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1058 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1059 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1060 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1061 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1062 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1063 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1064 /glade/derecho/scratch/djk2120/postp/c20250324/
