#!/bin/bash
#PBS -N ctsm6_lhc1110
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1110 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1111 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1112 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1113 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1114 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1115 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1116 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1117 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1118 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1119 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1120 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1121 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1122 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1123 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1124 /glade/derecho/scratch/djk2120/postp/c20250324/
