#!/bin/bash
#PBS -N ctsm6_lhc0270
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0270 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0271 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0272 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0273 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0274 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0275 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0276 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0277 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0278 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0279 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0280 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0281 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0282 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0283 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0284 /glade/derecho/scratch/djk2120/postp/c20250324/
