#!/bin/bash
#PBS -N ctsm6_lhc1365
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1365 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1366 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1367 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1368 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1369 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1370 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1371 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1372 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1373 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1374 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1375 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1376 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1377 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1378 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1379 /glade/derecho/scratch/djk2120/postp/c20250324/
