#!/bin/bash
#PBS -N ctsm6_lhc0315
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0315 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0316 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0317 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0318 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0319 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0320 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0321 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0322 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0323 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0324 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0325 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0326 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0327 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0328 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0329 /glade/derecho/scratch/djk2120/postp/c20250324/
