#!/bin/bash
#PBS -N ctsm6_lhc1425
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1425 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1426 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1427 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1428 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1429 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1430 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1431 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1432 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1433 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1434 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1435 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1436 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1437 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1438 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1439 /glade/derecho/scratch/djk2120/postp/c20250324/
