#!/bin/bash
#PBS -N ctsm6_lhc0810
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0810 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0811 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0812 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0813 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0814 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0815 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0816 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0817 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0818 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0819 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0820 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0821 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0822 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0823 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0824 /glade/derecho/scratch/djk2120/postp/c20250324/
