#!/bin/bash
#PBS -N ctsm6_lhc0900
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0900 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0901 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0902 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0903 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0904 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0905 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0906 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0907 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0908 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0909 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0910 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0911 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0912 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0913 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0914 /glade/derecho/scratch/djk2120/postp/c20250324/
