#!/bin/bash
#PBS -N ctsm6_lhc0855
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0855 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0856 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0857 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0858 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0859 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0860 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0861 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0862 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0863 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0864 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0865 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0866 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0867 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0868 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0869 /glade/derecho/scratch/djk2120/postp/c20250324/
