#!/bin/bash
#PBS -N ctsm6_lhc0015
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0015 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0016 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0017 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0018 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0019 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0020 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0021 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0022 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0023 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0024 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0025 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0026 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0027 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0028 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0029 /glade/derecho/scratch/djk2120/postp/c20250324/
