#!/bin/bash
#PBS -N ctsm6_lhc0600
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0600 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0601 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0602 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0603 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0604 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0605 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0606 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0607 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0608 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0609 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0610 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0611 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0612 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0613 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0614 /glade/derecho/scratch/djk2120/postp/c20250324/
