#!/bin/bash
#PBS -N ctsm6_lhc1065
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1065 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1066 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1067 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1068 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1069 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1070 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1071 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1072 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1073 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1074 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1075 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1076 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1077 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1078 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1079 /glade/derecho/scratch/djk2120/postp/c20250324/
