#!/bin/bash
#PBS -N ctsm6_lhc0915
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0915 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0916 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0917 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0918 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0919 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0920 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0921 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0922 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0923 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0924 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0925 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0926 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0927 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0928 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0929 /glade/derecho/scratch/djk2120/postp/c20250324/
