#!/bin/bash
#PBS -N ctsm6_lhc0150
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0150 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0151 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0152 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0153 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0154 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0155 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0156 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0157 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0158 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0159 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0160 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0161 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0162 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0163 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0164 /glade/derecho/scratch/djk2120/postp/c20250324/
