#!/bin/bash
#PBS -N ctsm6_lhc1380
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1380 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1381 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1382 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1383 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1384 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1385 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1386 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1387 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1388 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1389 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1390 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1391 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1392 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1393 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1394 /glade/derecho/scratch/djk2120/postp/c20250324/
