#!/bin/bash
#PBS -N ctsm6_lhc0075
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0075 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0076 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0077 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0078 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0079 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0080 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0081 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0082 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0083 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0084 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0085 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0086 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0087 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0088 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0089 /glade/derecho/scratch/djk2120/postp/c20250324/
