#!/bin/bash
#PBS -N ctsm6_lhc1095
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1095 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1096 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1097 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1098 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1099 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1100 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1101 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1102 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1103 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1104 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1105 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1106 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1107 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1108 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1109 /glade/derecho/scratch/djk2120/postp/c20250324/
