#!/bin/bash
#PBS -N ctsm6_lhc1290
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1290 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1291 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1292 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1293 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1294 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1295 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1296 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1297 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1298 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1299 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1300 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1301 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1302 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1303 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1304 /glade/derecho/scratch/djk2120/postp/c20250324/
