#!/bin/bash
#PBS -N ctsm6_lhc0660
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0660 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0661 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0662 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0663 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0664 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0665 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0666 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0667 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0668 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0669 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0670 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0671 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0672 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0673 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0674 /glade/derecho/scratch/djk2120/postp/c20250324/
