#!/bin/bash
#PBS -N ctsm6_lhc0255
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0255 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0256 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0257 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0258 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0259 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0260 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0261 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0262 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0263 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0264 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0265 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0266 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0267 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0268 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0269 /glade/derecho/scratch/djk2120/postp/c20250324/
