#!/bin/bash
#PBS -N ctsm6_lhc0330
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0330 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0331 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0332 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0333 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0334 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0335 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0336 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0337 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0338 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0339 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0340 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0341 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0342 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0343 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0344 /glade/derecho/scratch/djk2120/postp/c20250324/
