#!/bin/bash
#PBS -N ctsm6_lhc0420
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0420 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0421 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0422 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0423 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0424 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0425 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0426 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0427 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0428 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0429 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0430 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0431 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0432 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0433 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0434 /glade/derecho/scratch/djk2120/postp/c20250324/
