#!/bin/bash
#PBS -N ctsm6_lhc0510
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0510 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0511 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0512 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0513 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0514 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0515 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0516 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0517 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0518 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0519 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0520 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0521 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0522 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0523 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0524 /glade/derecho/scratch/djk2120/postp/c20250324/
