#!/bin/bash
#PBS -N ctsm6_lhc0675
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0675 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0676 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0677 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0678 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0679 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0680 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0681 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0682 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0683 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0684 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0685 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0686 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0687 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0688 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0689 /glade/derecho/scratch/djk2120/postp/c20250324/
