#!/bin/bash
#PBS -N ctsm6_lhc1035
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1035 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1036 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1037 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1038 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1039 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1040 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1041 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1042 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1043 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1044 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1045 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1046 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1047 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1048 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1049 /glade/derecho/scratch/djk2120/postp/c20250324/
