#!/bin/bash
#PBS -N ctsm6_lhc1170
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1170 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1171 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1172 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1173 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1174 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1175 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1176 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1177 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1178 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1179 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1180 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1181 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1182 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1183 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1184 /glade/derecho/scratch/djk2120/postp/c20250324/
