#!/bin/bash
#PBS -N ctsm6_lhc0045
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0045 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0046 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0047 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0048 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0049 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0050 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0051 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0052 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0053 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0054 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0055 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0056 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0057 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0058 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0059 /glade/derecho/scratch/djk2120/postp/c20250324/
