#!/bin/bash
#PBS -N ctsm6_lhc0630
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0630 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0631 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0632 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0633 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0634 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0635 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0636 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0637 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0638 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0639 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0640 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0641 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0642 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0643 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0644 /glade/derecho/scratch/djk2120/postp/c20250324/
