#!/bin/bash
#PBS -N ctsm6_lhc1335
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1335 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1336 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1337 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1338 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1339 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1340 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1341 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1342 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1343 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1344 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1345 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1346 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1347 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1348 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1349 /glade/derecho/scratch/djk2120/postp/c20250324/
