#!/bin/bash
#PBS -N ctsm6_lhc1470
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1470 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1471 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1472 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1473 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1474 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1475 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1476 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1477 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1478 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1479 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1480 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1481 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1482 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1483 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1484 /glade/derecho/scratch/djk2120/postp/c20250324/
