#!/bin/bash
#PBS -N ctsm6_lhc1005
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1005 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1006 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1007 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1008 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1009 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1010 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1011 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1012 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1013 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1014 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1015 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1016 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1017 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1018 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1019 /glade/derecho/scratch/djk2120/postp/c20250324/
