#!/bin/bash
#PBS -N ctsm6_lhc1260
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1260 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1261 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1262 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1263 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1264 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1265 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1266 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1267 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1268 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1269 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1270 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1271 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1272 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1273 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1274 /glade/derecho/scratch/djk2120/postp/c20250324/
