#!/bin/bash
#PBS -N ctsm6_lhc0390
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0390 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0391 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0392 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0393 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0394 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0395 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0396 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0397 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0398 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0399 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0400 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0401 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0402 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0403 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0404 /glade/derecho/scratch/djk2120/postp/c20250324/
