#!/bin/bash
#PBS -N ctsm6_lhc0735
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0735 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0736 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0737 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0738 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0739 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0740 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0741 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0742 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0743 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0744 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0745 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0746 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0747 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0748 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0749 /glade/derecho/scratch/djk2120/postp/c20250324/
