#!/bin/bash
#PBS -N ctsm6_lhc1455
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1455 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1456 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1457 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1458 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1459 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1460 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1461 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1462 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1463 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1464 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1465 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1466 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1467 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1468 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1469 /glade/derecho/scratch/djk2120/postp/c20250324/
