#!/bin/bash
#PBS -N ctsm6_lhc1440
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1440 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1441 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1442 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1443 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1444 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1445 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1446 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1447 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1448 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1449 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1450 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1451 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1452 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1453 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1454 /glade/derecho/scratch/djk2120/postp/c20250324/
