#!/bin/bash
#PBS -N ctsm6_lhc0135
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0135 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0136 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0137 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0138 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0139 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0140 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0141 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0142 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0143 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0144 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0145 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0146 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0147 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0148 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0149 /glade/derecho/scratch/djk2120/postp/c20250324/
