#!/bin/bash
#PBS -N ctsm6_lhc0930
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0930 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0931 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0932 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0933 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0934 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0935 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0936 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0937 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0938 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0939 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0940 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0941 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0942 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0943 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0944 /glade/derecho/scratch/djk2120/postp/c20250324/
