#!/bin/bash
#PBS -N ctsm6_lhc0585
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc0585 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0586 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0587 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0588 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0589 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0590 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0591 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0592 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0593 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0594 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0595 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0596 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0597 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0598 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc0599 /glade/derecho/scratch/djk2120/postp/c20250324/
