#!/bin/bash
#PBS -N ctsm6_lhc1245
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1245 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1246 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1247 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1248 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1249 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1250 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1251 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1252 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1253 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1254 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1255 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1256 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1257 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1258 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1259 /glade/derecho/scratch/djk2120/postp/c20250324/
