#!/bin/bash
#PBS -N ctsm6_lhc1485
#PBS -q casper
#PBS -l walltime=3:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -l select=1:ncpus=1

source ~/.bashrc
conda activate ppe-py


python postp_lhc_basic.py lhc1485 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1486 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1487 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1488 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1489 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1490 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1491 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1492 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1493 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1494 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1495 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1496 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1497 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1498 /glade/derecho/scratch/djk2120/postp/c20250324/
python postp_lhc_basic.py lhc1499 /glade/derecho/scratch/djk2120/postp/c20250324/
